### ISSUE TITLE
serving entry file with all imports

### ISSUE THREAD

**Issue by smnbbrv** [cartant/rxjs-tslint-rules#1]
Hi @cartant 

this looks like a really good solution.

However until the IDEs will support automatic import of `rxjs` operators and stuff, this is not really comfortable to use.

What I'd like to propose (and of course to have) is another setting in e.g. `tslint.json` that allows to specify the file, let's call it `rxjs-modules.ts` for instance, that contains all `rxjs` operators etc. for the particular project.

Of course, this `rxjs-modules.ts` should be imported in the beginning of `main.ts` so there is no race condition problem.

Is it possible to do so? Just to sum up:
1. We have some file e.g. `rxjs-modules.ts` which we set up as another property in `tslint.json`
2. This file is used to check every file in the project and it is end-programmer's responsibility to import this file before all other imports in his entry file.

Then everybody can decide for his project: whether to import everything inside of one single file or import it in each file separately.

**Comment by cartant** [comment]
@smnbbrv Thanks for the suggestion. Specifying all of the imports in a single file is a popular approach for adding RxJS operators and I can see how linting could be used to make it more robust.

Regarding the configuration, I think adding a `file` option to the `rxjs-add` rule ought to be sufficient:

    "rxjs-add": {
        "options": [{
            "file": "./rxjs-adds.ts"
        }],
        "severity": "error"
    }

If the file is specified, the imports within it would be used to determine which RxJS operators have been added.

I don't think it will be possible for the `rxjs-no-unused-add` rule to be used with a central file, as the TSLint rules are applied on a per-file basis. However, the `rxjs-add` rule alone ought to be pretty useful.

It should be pretty straightforward to implement, too. I'll see if I can find the time to do it in the next day or so.

**Comment by smnbbrv** [comment]
Hi, that would be super! I agree that unused imports cannot really be tracked here, however having the helper on rxjs-add would solve many problems

**Comment by cartant** [comment]
I've published version 1.1.0 which includes the `file` option. See the [`README`](https://github.com/cartant/rxjs-tslint-rules#options) for more information.

The change was really simple. However, TypeScript's backslash normalization and file case canonicalization caused the usual headaches.

**Comment by smnbbrv** [comment]
Cool!

**Comment by cartant** [comment]
@smnbbrv I've added some new options that are closely related to this issue. The detection of unused imports (mentioned in this issue) is now implemented. (See #2.)
