### ISSUE TITLE
rxjs-no-ignored-observable not working?

### ISSUE THREAD

**Issue by dpinol** [cartant/rxjs-tslint-rules#104]
Hi,
I'm not able to trigger the rxjs-no-ignored-observable rule, even with the code from your [fixture](https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-ignored-observable/default/fixture.ts.lint)

I use latest tslint 5.20 and rxjs-tslint-rules 4.25.0. I use rxjs 6.5.3
This is my tslint.json

`{
  "extends": [
    "rxjs-tslint-rules"
  ],
  "rules": {
    "rxjs-no-ignored-observable": true
  }
}
`

and my tsconfig

`
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "module": "es2015",
    "baseUrl": "./"
  }
}
`
thanks!

**Comment by cartant** [comment]
Works fine for me and the tests pass, so I'd have to guess what you might have done for it not to work and I don't have time to do that. It's likely more straightforward for you to look at the configurations in the passing tests to see if you can gain any insights into why it's 'not working' for you.
