### ISSUE TITLE
rxjs-no-compat not detecting rxjs-compat import for Observable.of

### ISSUE THREAD

**Issue by DaanKeun** [cartant/rxjs-tslint-rules#105]
Hi,

While attempting to adding the `rxjs-no-compat` rule to our list of RxJs rules we came across an issue where it was ignoring the rxjs-compat import for `Observable.of`

`import 'rxjs-compat/add/observable/of';`

Checking the current regex that detects invalid imports we noticed that currently the regex is not catering for `observable` namespace/directory in the import.

`!/^['"]rxjs\/(ajax|operators|testing|webSocket)['"]$/.test(moduleSpecifier.getText())`

**Comment by cartant** [comment]
I'm not sure what you mean. That regexp is for valid import locations and there is no valid `observable` location in v6 without `rxjs-compat`.

I'll have a look at the ignored `import 'rxjs-compat/add/observable/of` a little later.

**Comment by DaanKeun** [comment]
Ahh right, I see that now 🤦‍♂. 

Then I'm not sure why it is ignoring it. 
Our current workaround is to add 'rxjs-compat' into the import-blacklist which is working for now so no rush.

**Comment by cartant** [comment]
I added a test to attempt a reproduction of the issue, but the test passes, so ... 🤷‍♂ 
See https://github.com/cartant/rxjs-tslint-rules/issues/105

**Comment by DaanKeun** [comment]
For the test should the import not be `import 'rxjs-compat/add/observable/of';`?
Or am I misunderstanding how these tests work?

**Comment by cartant** [comment]
You've misunderstood. You use the old-style imports when using `rxjs-compat`. You should never have `rxjs-compat` in the import location. If you have a look in `node_modules/rxjs` you will find files in the places for the old import locations and those re-direct to `rxjs-compat`.

**Comment by DaanKeun** [comment]
Ahhh ok cool, thanks for taking the time looking into this 😄  and sorry for any wasted time

**Comment by cartant** [comment]
No worries.
