### ISSUE TITLE
Changlog has incorrectly named rules.

### ISSUE THREAD

**Issue by rgant** [cartant/rxjs-tslint-rules#110]
[Changelog](https://github.com/cartant/rxjs-tslint-rules/blob/master/CHANGELOG.md#features) specifies new rules named "rxjs-angular-prefer-takeuntil" and "rxjs-angular-prefer-composition", but actual rule names are "rxjs-prefer-angular-takeuntil" and "rxjs-prefer-angular-composition"

**Comment by cartant** [comment]
Fixed. Thanks.
