### ISSUE TITLE
Whitelist class property in rxjs-finnish based on decorator

### ISSUE THREAD

**Issue by klemenoslaj** [cartant/rxjs-tslint-rules#111]
Currently we have a whitelist of `rxjs-finnish` rule based on `names` and `types`. I wonder if it would be possible to whitelist a class property based on the presence of a decorator?

Use case: In Angular some fields are decorated with `@Output` and it would be super strange for these fields to have `$` suffix.

**Comment by cartant** [comment]
My understanding was that `@Output` properties have the `EventEmitter` type, so the type-based whitelist should suffice. Is that not the case?

**Comment by klemenoslaj** [comment]
> My understanding was that `@Output` properties have the `EventEmitter` type, so the type-based whitelist should suffice. Is that not the case?

That is true and while not considered best practice I saw often people use `Subject` or a piped `Observable` as an output. In this case we cannot limit to the type.

I actually use it sometimes, because it makes my code a bit cleaner.

**Comment by cartant** [comment]
I'm not keen on encouraging or supporting something that's not best practice, so no, I'm not inclined to extend the rule's options in this way.
