### ISSUE TITLE
Not so opinionated analog of `rxjs-prefer-angular-takeuntil`, please

### ISSUE THREAD

**Issue by anotherpit** [cartant/rxjs-tslint-rules#115]
I'd like to suggest an idea of a bit less restrictive analog of `rxjs-prefer-angular-takeuntil`.

Since there are a plenty of libraries offering some automation for creating and completing destroy subjects (https://www.npmjs.com/search?q=take%20until%20destroyed), I'd like to have a rule that only checks that `.subscribe()` in component is preceded by `.takeUntil()` (or any of its configurable aliases) in `.pipe()`. And doesn't check destroy subject, `ngOnDestroy()`, `.next()` and `.complete()` calls, and whatever else `rxjs-prefer-angular-takeuntil` currently checks.

Perhaps, might be achieved by adding more options to existing `rxjs-prefer-angular-takeuntil` rule. Or by implementing a completely separate new rule. What do you think?

**Comment by cartant** [comment]
Yeah, that sounds pretty reasonable. 4.30.0 has been published and the rule now has `alias` and `checkDestroy` options.

**Comment by anotherpit** [comment]
@cartant 

I've just checked out new version, and tried to run against my repo. Experiencing some issues. Even if `checkDestroy` is set to false the rule _does_ still check subject and _is_ still opinionated about operator signature. Let me adapt code from your tests to demonstrate:

```ts
// Alias accepts component instance, not destroy subject
const someAlias = (cmp) => takeUntil(cmp.destroy);

@Component({
  selector: "component-with-alias"
})
class CorrectComponent implements OnDestroy {
  private destroy = new Subject<void>();
  someMethod() {
    a.pipe(
      switchMap(_ => b),
      someAlias(this)
    ).subscribe();
  }
  ngOnDestroy() {
    this.destroy.next();
    this.destroy.complete();
  }
}
```

```json
{
  "rules": {
    "rxjs-prefer-angular-takeuntil": {
      "options": [{
        "alias": ["someAlias"],
        "checkDestroy": false
      }]
    }
  }
}
```

My suggestion is to disable any semantic checks and any assumptions about operator's signature when `checkDestroy` is set to false.

**Comment by cartant** [comment]
@anotherpit Added a test with your snippet and config - https://github.com/cartant/rxjs-tslint-rules/tree/master/test/v6/fixtures/issues/115 - and AFAICT it passes, so I'm not sure what the issue is.

**Comment by anotherpit** [comment]
Well, it actually passes even without any `takeUntil` operator at all. I'm doing further investigations.

**Comment by anotherpit** [comment]
@cartant The test always passed because of missing declarations of `a` and `b`

Here's a fixture replacement to make it fail:
```ts
import { Component } from "@angular/core";
import { of, Subject } from "rxjs";
import { switchMap, takeUntil } from "rxjs/operators";

const a = of("a");
const b = of("b");

const someAlias = (cmp) => takeUntil(cmp.destroy);

@Component({
  selector: "component-with-alias"
})
class CorrectComponent implements OnDestroy {
  private destroy = new Subject<void>();
  someMethod() {
    a.pipe(
      switchMap(_ => b),
      someAlias(this)
    ).subscribe();
  }
  ngOnDestroy() {
    this.destroy.next();
    this.destroy.complete();
  }
}

[prefer-takeuntil]: Subscribing without takeUntil is forbidden
```

Would you mind reopening this issue?

**Comment by anotherpit** [comment]
And here's some extreme case that I suppose should also pass when `checkDestroy` is false:

```ts
import { Component } from "@angular/core";
import { of } from "rxjs";
import { switchMap } from "rxjs/operators";

const a = of("a");
const b = of("b");

const someAlias = (nevermind?: string, the?: boolean, signature?: number) => {}

@Component({
  selector: "component-with-alias"
})
class CorrectComponent {
  someMethod() {
    a.pipe(
      switchMap(_ => b),
      someAlias()
    ).subscribe();
  }
}

[prefer-takeuntil]: Subscribing without takeUntil is forbidden

```

**Comment by cartant** [comment]
@anotherpit This should be fixed in 4.30.1 and `checkDestroy` should default to `false` if an `alias` is specified.

**Comment by anotherpit** [comment]
@cartant I do confirm: now it works on my repo. Thanks.

**Comment by cartant** [comment]
@anotherpit No worries.
