### ISSUE TITLE
Allow DOMExceptions with rxjs-throw-error

### ISSUE THREAD

**Issue by chrisguttandin** [cartant/rxjs-tslint-rules#117]
I would like to propose to allow `DOMException`s to be thrown where `rxjs-throw-error` currently only allows an instance of an `Error`. I think they serve the same purpose.

For some reason a `DOMException` is not extending an `Error` in TypeScript. However in JavaScript this seems to be true:

```js
(new DOMException()) instanceof Error // true
```

**Comment by cartant** [comment]
Should be done in 4.34.1.

**Comment by chrisguttandin** [comment]
Many thanks.
