### ISSUE TITLE
Feature Request > Remove RxJS as a Peer Dependency

### ISSUE THREAD

**Issue by wSedlacek** [cartant/rxjs-tslint-rules#118]
https://github.com/cartant/rxjs-tslint-rules/blob/4bffc8738fb2f9e20cfc685c7ab414744c2ae119/package.json#L56

Would it be possible to remove RxJS as a peer dependency?
I would like to use this as part of my default ruleset however I would like to avoid false positive warnings when installing.
As far as I can tell the rule set doesn't directly depend on RxJS, at least in my brief scan through the dependencies.

While we are at it we should also bump the TypeScript peer dependency on both this, and `tslint-etc`.

**Comment by cartant** [comment]
Done.

**Comment by cartant** [comment]
Be aware, though, that you will see console warnings if you have RxJS rules enabled in your config, but don't have it installed: https://github.com/cartant/rxjs-tslint-rules/blob/172bc681de10daab2c55e75bf405eb424ad8860f/source/support/peer.ts#L19-L30

However, TSLint prints so many tedious warnings to the console that it's probably not any issue.

**Comment by wSedlacek** [comment]
All good! I checking `require.resolve()` to determine if `rxjs` (and others) are installed to determine what rule dictionary and rules to use.

Thank you for the warning though!
