### ISSUE TITLE
rxjs-no-patched toPromise must not emit error

### ISSUE THREAD

**Issue by Delagen** [cartant/rxjs-tslint-rules#12]
`toPromise` is now base method of Observable due 5.5.0-beta.5

**Comment by cartant** [comment]
Wow, you were super fast raising that! Congratulations.

I'll have a think about the best way of fixing this. It should be possible to sniff the RxJS version, as the rules already resolve RxJS to its `node_modules` location to read the files in the `add/operator` directory, etc. Reading the version from the `package.json` should be simple enough.

In the interim, I guess that's life on the bleeding edge.

**Comment by cartant** [comment]
Should be fixed in 3.0.2. Re-open if otherwise.
