### ISSUE TITLE
rxjs-prefer-angular-takeuntil doesn't work with param "this"

### ISSUE THREAD

**Issue by retoforte** [cartant/rxjs-tslint-rules#121]
Hi, I have been trying to implement rxjs-prefer-angular-takeuntil by using an alias like this one "untilDestroyed", but if the param is a reference with the keyword "this" it doesn't work.

Sample
let otroObservable = of('a');
    const sub: Observable<true> = new Observable();
    sub.pipe(untilDestroyed(this)).subscribe(() => {
      console.log('demo');
    });
    
  Is there a way of making this work?

**Comment by cartant** [comment]
See #115.
