### ISSUE TITLE
Error: Cannot find 'rxjs.imports.ts' in the compiled program. Has it been imported?

### ISSUE THREAD

**Issue by tlaak** [cartant/rxjs-tslint-rules#17]
I'm getting this error when running the linter:

```
Error: Cannot find '/path/to/app/src/rxjs.imports.ts' in the compiled program. Has it been imported?
    at Walker.findSourceFile (/path/to/app/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:136:15)
    at Walker.walkFile (/path/to/app/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:146:35)
    at Walker.onSourceFileEnd (/path/to/app/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:48:31)
    at Walker.AddedWalker.visitNode (/path/to/app/node_modules/rxjs-tslint-rules/dist/support/added-walker.js:41:18)
    at Walker.SyntaxWalker.walk (/path/to/app/node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (/path/to/app/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
    at Rule.applyWithProgram (/path/to/app/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:15:21)
    at Linter.applyRule (/path/to/app/node_modules/tslint/lib/linter.js:174:29)
    at /path/to/app/node_modules/tslint/lib/linter.js:119:85
    at Object.flatMap (/path/to/app/node_modules/tslint/lib/utils.js:151:29)
```
The linter found the errors though and I could fix the problems, but I'm still getting this. I have added the `rxjs-add` ruleset following the instructions in the README file and I've imported my `rxjs.imports.ts` file in `main.ts`, just like in the example code.

**Comment by cartant** [comment]
Are you using Angular's CLI? Have you read the [section in the README](https://github.com/cartant/rxjs-tslint-rules#angularcli) that deals with the Angular CLI? It runs the linting in three passes with three separate configurations.

**Comment by tlaak** [comment]
Yeah I checked that, but I only have one tslint.json file in the project.

**Comment by cartant** [comment]
You should read it again; the `tsconfig.json` files are also important.

The repo contains a working, CLI-generated example. To see precisely what was changed in the CLI-generated app, have a look at [this commit](https://github.com/cartant/rxjs-tslint-rules/commit/73872cc381765d2fcc9fc22cb686128b76dfd6fb) - which is also referenced in the README.

**Comment by tlaak** [comment]
Okay, I'll take a look again. Thanks!

**Comment by tlaak** [comment]
Solved, I was missing the `"files": ["rxjs.imports.ts", "test.ts"],` setting in my `tsconfig.spec.json` file.

**Comment by cartant** [comment]
No worries.

**Comment by bjohnson-va** [comment]
For others who came searching, like me:
Make sure you add 
```
"files": [
    "rxjs.imports.ts"
  ]
```
... to your *E2E* config file, too.  (`tsconfig.e2e.json`)

**Comment by bjohnson-va** [comment]
@cartant I can't tell.  

Are you saying that I shouldn't need to update tsconfig.e2e.json?
Or, that you have mentioned my above prescription somewhere in the readme.  Because you haven't.

**Comment by cartant** [comment]
@bjohnson-va My comment was a little too terse (and perhaps rude, but that wasn't my intention).

I'd recommend disabling the rule instead, as it simply isn't required for the e2e tests. The mechanism for doing so is outlined in the README. Basically, you can create a `tslint.json` file at any level and the Angular CLI's linting task will find it - if its location in the directory hierarchy is at or above that of the file being linted. So it's easy to override the rules for the e2e tests.

For me, this seems to be a smaller change and less of a workaround than adding an empty imports file and adding that file to the `tsconfig.e2e.json`.

Also, recommending the workaround would surely see some devs attempt to add their `src/rxjs.imports.ts` file to `tsconfig.e2e.json` and that would effect errors if they have `allowUnused: false` in the rule's options.

**Comment by bjohnson-va** [comment]
Strange.  That's not the behaviour I was seeing.

I'm not able to share my project's actual code.  I can try to spin up an example repo later.

For now, my project's *current* pseudo-structure (i.e. only including relevant files) is:
```
my-project/
  e2e/
    tsconfig.e2e.json
    tslint.e2e.json
  src/
    app/
    main.ts
    tsconfig.app.json
    tsconfig.spec.json
  tsconfig.json
  tslint.json
```

`tsconfig.e2e.json` contains:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/e2e",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "jasmine",
      "jasminewd2",
      "node"
    ]
  },
  "files": [
    "rxjs.imports.ts"
  ]
}
```

`tslint.e2e.json`
```
{
  "extends": ["../tslint.json"],
  "rules": {
    "rxjs-add": { "severity": "off" }
  }
}
```

`main.ts`
```
import './rxjs.imports';
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));
```

`tsconfig.app.json`
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

`tsconfig.spec.json`
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "jasmine",
      "jasmine-expect",
      "node"
    ]
  },
  "files": [
    "rxjs.imports.ts",
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

`tsconfig.json`
```
{
  "compileOnSave": false,
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "fullTemplateTypeCheck": true
  },
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strict": true,
    "pretty": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

`ng lint` runs fine with the above configuration. 

# Problem

If I remove the aforementioned "files" line from `tsconfig.e2e.json`, I get:
```
$npm run lint

> my-project@0.0.0 lint /Users/X/Projects/my-project
> ng lint

Error: Cannot find '/users/x/projects/my-project/src/rxjs.imports.ts' in the compiled program. Has it been imported?
    at Walker.findSourceFile (/Users/X/Projects/my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:136:15)
    at Walker.walkFile (/Users/X/Projects/my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:146:35)
    at Walker.onSourceFileEnd (/Users/X/Projects/my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:48:31)
    at Walker.AddedWalker.visitNode (/Users/X/Projects/my-project/node_modules/rxjs-tslint-rules/dist/support/added-walker.js:41:18)
    at Walker.SyntaxWalker.walk (/Users/X/Projects/my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (/Users/X/Projects/my-project/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
    at Rule.applyWithProgram (/Users/X/Projects/my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:15:21)
    at Linter.applyRule (/Users/X/Projects/my-project/node_modules/tslint/lib/linter.js:174:29)
    at /Users/X/Projects/my-project/node_modules/tslint/lib/linter.js:119:85
    at Object.flatMap (/Users/X/Projects/my-project/node_modules/tslint/lib/utils.js:151:29)


All files pass linting.
```

**Comment by cartant** [comment]
@bjohnson-va Unless the Angular CLI's configuration has been changed, `tslint.e2e.json` should be named `tslint.json`. 

The CLI uses TSLint's [`Configuration`](https://github.com/palantir/tslint/blob/5.9.1/src/configuration.ts) class to [search for relative configuration files](https://github.com/angular/angular-cli/blob/v1.7.3/packages/%40angular/cli/tasks/lint.ts#L84) and the name of the TSLint configuration file is unrelated to the name of the TypeScript configuration file. (Well, it was unrelated when I prepared [the CLI example](https://github.com/cartant/rxjs-tslint-rules/tree/v3.15.0/examples/ng-cli-example) in this repo.)

**Comment by bjohnson-va** [comment]
Very possible.  I generated this project several months ago.

**Comment by bjohnson-va** [comment]
I don't actually have any e2e tests at the moment, so removing my `tsconfig.e2e.json` and renaming `tslint.e2e.json` => `tslint.json` did the trick.

Thanks for the insight.

**Comment by cartant** [comment]
@bjohnson-va You shouldn't need to remove `tsconfig.e2e.json`. Angular creates that file. It doesn't - unless things have very recently changed - create a TSLint configuration file in the `e2e` directory. You can create that file to disable the RxJS-related rule (using TSLint's relative-configuration-file mechanism).

I would not recommend removing `tsconfig.e2e.json`, even if you are not using end-to-end tests.
