### ISSUE TITLE
Is this library obsolete now that RxJs 5.5.2 ships with lettable operators?

### ISSUE THREAD

**Issue by Karankang007** [cartant/rxjs-tslint-rules#20]
https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

**Comment by cartant** [comment]
No. It can be used to enforce a policy that prevents non-lettable operators from being used. Said rules are outlined at the end of [this article](https://blog.angularindepth.com/rxjs-understanding-lettable-operators-fe74dda186d3).

When v6 is released, I expect the prototype-patching operators to be removed and, at that stage, most of the rules in this package will be redundant.

However, it also contains a bunch of rules that don't relate to importing the prototype patching operators - for situations I'd like to be warned about, etc.
