### ISSUE TITLE
Beware of `flatMap` exported from `rxjs/add/operator/mergeMap`

### ISSUE THREAD

**Issue by watiko** [cartant/rxjs-tslint-rules#21]
https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/mergeMap.ts#L6

When I use `flatMap` instead of `mergeMap` still needs `import 'rxjs/add/operator/mergeMap'`.
However I got following error.

```
Unused patched operator in ./src/rxjs.imports.ts: mergeMap
```

**Comment by cartant** [comment]
Should be fixed in 3.1.3.
