### ISSUE TITLE
Unused patched operator in ./src/rxjs.imports.ts: switchMap

### ISSUE THREAD

**Issue by kamok** [cartant/rxjs-tslint-rules#23]
I'm getting this error with the switchMap operator.

I have plenty of other operators in `rxjs.imports.ts` so it's not any other issues except for switchMap.

I DO use switchMap in the application.

Perhaps this is the same problem with the flatMap issue? I'm not sure. I'm going to refactor the code to not use switchMap as the person who used it said they didn't use it for switchMap's intended purpose.

**Comment by cartant** [comment]
Be ware that [this gotcha](https://github.com/cartant/rxjs-tslint-rules#observablecreate) can effect false positives for unused patches. Similarly, if the observable instance to which the patched operator is applied is not typed as an `Observable` the static analysis will not consider it to be a use of the operator.

**Comment by kamok** [comment]
Thank you for clarifying this: 

> Similarly, if the observable instance to which the patched operator is applied is not typed as an `Observable` the static analysis will not consider it to be a use of the operator.

This was NOT appended to `Observable`, but an Angular library object.

I am closing this.

**Comment by cartant** [comment]
> This was NOT appended to Observable, but an Angular library object.

I should have said that the type needs to `Observable` or an `Observable`-derived type. The real problem is when patched operators are used with values that have `any` as their type. The static analysis won't consider them to be observables.

What was the Angular object that effected the unused error? If it's not `any`, what is it?

**Comment by kamok** [comment]
@cartant It was a `paramMap` from a `ActivatedRoute`
