### ISSUE TITLE
Rule for Finnish Notation in Observables names

### ISSUE THREAD

**Issue by HideDev** [cartant/rxjs-tslint-rules#24]
This is a very controversial approach among programmers. But it has the right to life. 
The rule should either allow only Finnish Notation for Observables or deny.
https://medium.com/@benlesh/observables-and-finnish-notation-df8356ed1c9b

**Comment by cartant** [comment]
Nice suggestion. I'll have a think about it; it should be pretty easy to implement.

**Comment by cartant** [comment]
Do you use Finnish notation?

What are the rules for what should have a suffix and what should not?

I guess variables, properties, property getters and setters, and parameters, but is there anything else? This has the potential to open a can of worms.

**Comment by HideDev** [comment]
We do not use it now, just thinking about it.

**Comment by listepo** [comment]
Hi, any news?)

**Comment by cartant** [comment]
@listepo This probably won't be something I'll implement unless someone can tell me the situations in which a `$` suffix is supposed to be enforced. (See my comment above.) I don't use Finnish notation, so I'm unaware of  any generally accepted practices. And I'm not super keen on adding lots of configuration.

**Comment by listepo** [comment]
@cartant I think @benlesh could help with this

**Comment by listepo** [comment]
@cartant  maybe this [url](https://blog.strongbrew.io/rxjs-best-practices-in-angular/)  article will help you

**Comment by cartant** [comment]
@listepo Hmm, I'm not sure bothering Ben is worthwhile. In his [Observables and Finnish Notation](https://medium.com/@benlesh/observables-and-finnish-notation-df8356ed1c9b) article, he states:

> Well, I’m personally not a fan.

And that article states that the:

> idea here is that you pluralize all variable names that contain observables.

With "pluralize" implying an appended `$`. So I guess that means everything - including functions that return observables - as in the article you linked in your comment.

However, that creates a real problem, as there are many functions in the RxJS API that don't have a `$`, but do return an observable. So any rule would have to differentiate between RxJS functions and user-land functions.

Frankly, this is sounding too hard.

**Comment by benlesh** [comment]
Externally, I use Finnish notation. Internally, it's not used at Google.

I'm really on the fence about it. I'm not sure it should be required, but it could be an option.

**Comment by cartant** [comment]
Actually, this was much simpler than I thought it would be.

Version 3.4.0 now includes an `rxjs-finnish` rule (for you guys) and an `rxjs-no-finnish` rule (for me :smile: ).

**Comment by cartant** [comment]
@listepo @HideDev No worries.

Just beware that the rule insists that functions that return observables also get the `$` suffix - as per the articles linked in comments above.

For examples of what's enforced, see this [fixture](https://github.com/cartant/rxjs-tslint-rules/blob/master/fixtures/finnish-with-%24/fixture.ts) source file.
