### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by maxime1992** [cartant/rxjs-tslint-rules#29]
It has been such an amazing help on a huge Angular project...

Would be really awesome with auto fix but still, super helpful.

Thanks a lot!

**Comment by cartant** [comment]
No worries.

#10 requested automatic fixing. However, as pipeable operators are now preferred and the patching mechanism is not encouraged, it's unlikely I'll be implementing it. The only rules that I can see that could have automatic fixes are `rxjs-add` and `rxjs-no-unused-add`. And only when **not** using a central file of imports. Out of curiosity, is that your situation?

**Comment by maxime1992** [comment]
Yes I usually prefer to have a central file but the project I've been working on doesn't have that
