### ISSUE TITLE
rxjs-just rationale

### ISSUE THREAD

**Issue by buu700** [cartant/rxjs-tslint-rules#48]
It would be helpful to a have a sentence or so describing the rationale for this new rule in the readme. Should `just` be generally preferred as a best practice / is `or` deprecated, or is this just a rule for projects that happen to have already standardized on `just` for whatever reason?

(Neither of those words is very googleable, so finding those answers myself isn't very straightforward.)

**Comment by cartant** [comment]
Yeah, it could do with an explanation. Some background: https://github.com/ReactiveX/rxjs/issues/3747

**Comment by buu700** [comment]
That definitely helps clear things up, thanks!

**Comment by cartant** [comment]
I'll update the README later today.
