### ISSUE TITLE
Error: Cannot find ./src/rxjs.imports.ts

### ISSUE THREAD

**Issue by herkulano** [cartant/rxjs-tslint-rules#5]
Getting this error every time although it works and shows lint errors.

Log:
```
Error: Cannot find ./src/rxjs.imports.ts
    at Walker.findSourceFile (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:134:15)
    at Walker.walkFile (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:144:35)
    at Walker.onSourceFileEnd (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:48:31)
    at Walker.AddedWalker.visitNode (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/rxjs-tslint-rules/dist/support/added-walker.js:40:18)
    at Walker.SyntaxWalker.walk (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/tslint/lib/language/rule/abstractRule.js:31:16)
    at Rule.applyWithProgram (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:15:21)
    at Linter.applyRule (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/tslint/lib/linter.js:176:29)
    at /Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/tslint/lib/linter.js:121:85
    at Object.flatMap (/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/tslint/lib/utils.js:151:29)

ERROR: /Users/Herc/Documents/RADAR/RADAR-Dashboard/src/app/components/charts/chart-base/chart-base.component.ts[78, 8]: RxJS add import is missing from ./src/rxjs.imports.ts: debounceTime
```

Also had to add `"no-unused-variable": false,` to tslint for `"allowUnused": false` to work properly.

**Comment by cartant** [comment]
`no-unused-variable` has some major problems. It somehow messes with TypeScript. See #4 for more information. When I have the time, I might have a look at it and file another issue with TSLint, but that particular rule has wasted a lot of my time in the past and looking further into it is not something I relish.

Regarding the error relating to `./src/rxjs.imports.ts`, the path specified for the central imports file needs to be relative to the `tsconfig.json` file. Are you sure that you are specifying a `tsconfig.json`-relative path?

**Comment by herkulano** [comment]
@cartant yes, you can check it here:
https://github.com/RADAR-CNS/RADAR-Dashboard/pull/240/files#diff-ace19bd0c04529e685320269e3c05de9R61

As it's an angular-cli project it has a main tsconfig in the root and then a tsconfig inside `./src` that extends the main tsconfig, don't know if this could be the cause of the problem.
https://github.com/RADAR-CNS/RADAR-Dashboard/blob/develop/tsconfig.json
https://github.com/RADAR-CNS/RADAR-Dashboard/blob/develop/src/tsconfig.app.json

**Comment by cartant** [comment]
Thanks. Yeah, it sounds like that could be the problem. I think the path will need to be relative to whichever `tsconfig` file is supplied to TSLint. And it sounds like that might be `src/tsconfig.app.json`.

I would try specifying `./rxjs.imports.ts` as the path to the central file. If that doesn't solve the problem, I will have look into it tomorrow - my time - as it's getting late, here.

Either way, I'll improve the error message to include the absolute path that it's using to look for the file.

**Comment by herkulano** [comment]
Forgot to mention that I also tried `./rxjs.imports.ts` but get the same error and then the lint errors do not work.

Thanks a lot for looking into this!

**Comment by cartant** [comment]
No worries. I'll have a look at it tomorrow.

**Comment by cartant** [comment]
The problem is that the Angular CLI runs TSLint three times:

* first, with application files from `src/`;
* then with the test files from `src/`;
* and, finally, with files from `e2e/`.

If the central imports file is not included in the tests, it's not available in the compiled TypeScript program that TSLint provides to the rules.

You can fix the problem be importing `./src/rxjs.imports.ts` in `test.ts`:

```ts
import './rxjs.imports';
```

and in `e2e/app.po.ts`:

```ts
import '../src/rxjs.imports';
```

I'll improve the error thrown by the rule to better describe the situation.

**Comment by herkulano** [comment]
@cartant thank you so much, it works great now!

**Comment by cartant** [comment]
No worries.

**Comment by cartant** [comment]
@herkulano You might be interested in [this issue](https://github.com/cartant/rxjs-tslint-rules/issues/8) and [this comment](https://github.com/cartant/rxjs-tslint-rules/issues/8#issuecomment-329950467). It introduces a somewhat cleaner way of making the `rxjs-add` rule play nice with `@angular/cli`.

**Comment by kamok** [comment]
@cartant I think you should add to the README: `You can fix the problem by importing ./src/rxjs.imports.ts in test.ts:`

`import './rxjs.imports';`

As you've written above. My tests will complain about not finding the rxjs imports otherwise.

**Comment by cartant** [comment]
@kamok The `README.md` contains a workaround in the [`@angular/cli` gotchas](https://github.com/cartant/rxjs-tslint-rules#angularcli) section. I've recommended adding it to the `src/tsconfig.spec.json` file. I thought that was a cleaner solution, but that's debatable. I will add a note inline with your comment. Thanks.

**Comment by kamok** [comment]
@cartant I have no idea why mine didn't work when I added it to the files array of `tsconfig.spec.json`. Maybe its only my app, but adding it to `test.ts` did the trick for me.
