### ISSUE TITLE
No errors at all

### ISSUE THREAD

**Issue by Olgagr** [cartant/rxjs-tslint-rules#53]
I added ```rxjs-tslint-rules``` to my dev dependencies. Then I added to my tslint.json file:

```
  "extends": [
    "tslint:recommended",
    "tslint-config-prettier",
    "rxjs-tslint-rules"
  ],
  ...
  rules: {
     "rxjs-add": {
      "options": {
        "allowElsewhere": false,
        "allowUnused": false,
        "file": "./src/rxjs-imports.ts"
      },
      "severity": "error"
    }
  }
```

I removed ```no-unused-variable``` declaration from tslint.json.

Right now, in the project, rxjs imports are in many files. I want to force the rule to have one central file with imports. However, when I run linting:

```
npm run tslint "src/**/*.ts"
```
I see a warning: ```Warning: The 'rxjs-add' rule requires type information.```
I see no errors at all. Moreover, VS Code shows no errors. I'm not using Angular CLI. 

tslint version: 5.8.0
rxjs-tslint-rules: version 4.7.0

**Comment by cartant** [comment]
As stated by the warning, the rule needs type information. See [the TSLint docs](https://palantir.github.io/tslint/usage/type-checking/) to see how to enable it.

**Comment by Olgagr** [comment]
@cartant They stayed in this comment that they are removing type checking as a feature of TSLint: https://github.com/palantir/tslint/issues/3399#issuecomment-339745317

**Comment by cartant** [comment]
The `--type-check` command line flag might be deprecated, but rules are still able to rely upon and use type information and for that a project file needs to be specified - see the documentation link in my previous comment to see how. If a project file is not specified, type information is not available to the rule and it simply cannot do what it needs to do. TSLint will see in the [rule's metadata that type information is required](https://github.com/cartant/rxjs-tslint-rules/blob/v4.7.0/source/rules/rxjsAddRule.ts#L37) and it will skip the rule and emit the warning that you've seen.

**Comment by Olgagr** [comment]
Ok, thank you for the explanation! :)
