### ISSUE TITLE
Error using TypeScript TSLint Language Service Plugin

### ISSUE THREAD

**Issue by nicolashenry** [cartant/rxjs-tslint-rules#59]
I have some side effects in Visual Studio Code using some rules of rxjs-tslint-rules through this [typescript service plugin](https://github.com/Microsoft/typescript-tslint-plugin).

See the discussion [here](https://github.com/Microsoft/typescript-tslint-plugin/issues/8) to have all the details.

**Comment by cartant** [comment]
> I think that this is maybe caused by the `@phenomnomnominal/tsquery` module used by `rxjs-tslint-rules` in some rules which seems to modify typescript nodes here.

Have you filed this against `@phenomnomnominal/tsquery`? There's not much I can do about it here.

Although, I will talk with that package's author about refactoring to use a `WeakMap` instead of mutating the nodes. IMO, that would be the simplest way for him to solve the problem.

**Comment by cartant** [comment]
I'm unable to reproduce the problem using your minimal repro and VS Code 1.28.2 and TypeScript TSLint Plugin 0.0.2.

What exactly does this mean?

> I get this error in Typescript output console in Visual Studio Code ...

**Comment by nicolashenry** [comment]
The thing was not about rxjs but about occurrence highlighting in Visual Studio Code, this why I initially reported it on typescript-tslint-plugin and not here.

![test](https://user-images.githubusercontent.com/139160/47593271-fd123f80-d976-11e8-8064-28ac7977dbca.gif)

**Comment by nicolashenry** [comment]
Here is what happens when rxjs-tslint-rules are disabled : 

![test2](https://user-images.githubusercontent.com/139160/47593712-968e2100-d978-11e8-98f5-3d18748e87f4.gif)

**Comment by nicolashenry** [comment]
@cartant Don't forget to follow [instructions](https://github.com/Microsoft/typescript-tslint-plugin#with-vs-code) from the plugin, in particular selecting the workspace typescript version.

**Comment by cartant** [comment]
Now I see what you mean regarding the output. I was about to reply that I still could not reproduce the problem, but when I flipped back to VS Code to take a screenshot, I saw an error written to the console.

However, I have not been able to make it error again. This will make it essentially impossible to verify whether or not the change I've made to `tsquery` solves the problem.

Do you have a reliable sequence for reproducing the error?

**Comment by cartant** [comment]
BTW, if you want to try out `tsquery` with my change, you can have a look at this branch:

https://github.com/cartant/tsquery/tree/weak-map

However, I'd still like to verify, for myself, that the change solves the problem. I'd need to make another small change before submitting a PR and the package owner will have to think about it, as it'll technically be a breaking change.

**Comment by cartant** [comment]
It's a TypeScript package, so you cannot use npm to install it directly. You'll have to clone the repo, build it yourself, and then copy it to `node_modules`, etc. There's likely a bit more to it than that, as it depends upon what Craig is doing in his build and his distribution. Your best bet is to build the cloned repo, find the distribution files within it and overwrite those that are in your `node_modules` directory - making sure that you reinstall `tsquery` normally, first.

**Comment by nicolashenry** [comment]
Ok I retried by cloning it, building it apart and using "npm link" and it seems to be ok!

![test4](https://user-images.githubusercontent.com/139160/47595682-c7bf1f00-d981-11e8-9422-8fc378b3d697.gif)

**Comment by cartant** [comment]
Awesome. I'll try to verify it myself and will then ready a PR and talk with Craig about the breaking change, etc.

**Comment by nicolashenry** [comment]
I tried with rxjs-tslint-rules 4.10.1 and I confirm that the problem is fixed 🎉. Thank you ☺️
