### ISSUE TITLE
Warning for prefer async pipe over subscibe

### ISSUE THREAD

**Issue by jaikishore08** [cartant/rxjs-tslint-rules#66]
I am using rxjs lint configuration and i am getting warning 'rxjs-prefer-async-pipe' over subscribe. Can i ignore this warning or do i need to remove the subscribe operator from my component. Please suggest.

**Comment by cartant** [comment]
If the warning isn't appropriate, you should not enable the rule.

It's possible to write Angular applications with no - or, at least, very few - explicit `subscribe` calls. But whether or not you should is a matter of opinion.

At the moment, there is no recommended configuration and no rules should be enabled by default. I would suggest that you resolve the problem by not enabling the rule.
