### ISSUE TITLE
rxjs-all-subjects-private addition

### ISSUE THREAD

**Issue by maggie-x** [cartant/rxjs-tslint-rules#72]
Wrote a rule `rxjs-all-subjects-private` to enforce that the access level modifier of subjects which are class properties to be private, based off the `rxjs-finnish` rule. 

e.g.

```
class Mock {
  public propertySubject$ = new Rx.Subject<any>();
         ~~~~~~~~~~~~~~~~     [Subject 'propertySubject$' must be private.]
}
```

Would this be something of interest to integrate?

**Comment by cartant** [comment]
Sure. If you want to open a PR, that would be great. Please include some tests, though.

**Comment by maggie-x** [comment]
If you needed a bit more context behind this rule, enforcing subjects to always be `private` members of a class rather than `public` makes it generally easier to reason about your code if a subject doesn't leak outside the scope of your class (i.e. you only need to scan the current file for calls to `.next` rather than across the codebase).

Awesome, will work on it now :)

**Comment by cartant** [comment]
My only request would be for the name of the rule to be more like the names that are already used. Could I suggest `rxjs-no-public-subjects`? What do you think?

**Comment by maggie-x** [comment]
Sure thing! Will change the name :+1:

**Comment by cartant** [comment]
BTW, for the tests, only concern yourself adding them to the `test/v6` directory. Don't worry about `test/v5` and `test/v6-compat` directories.

**Comment by maggie-x** [comment]
Just realised, changing to `rxjs-no-public-subjects` slightly changes the logic of the lint rule. The rule now suggests that `protected` level subjects are allowable. Doesn't really make a difference to my current project, but what are your thoughts on this?

**Comment by cartant** [comment]
TBH, I don't mind if the rule is named `rxjs-no-public-subjects` and uses your unchanged implementation. That is, I don't mind if the rule also effects failures for `protected` subjects.

I'd consider `protected` subjects to be a code smell.

If someone wants to use the rule, but allow `protected` subjects, I can add an `allowProtected` option at a later date.

**Comment by cartant** [comment]
If you want you could consider renaming the rule (again ... sorry) to something like `rxjs-no-exposed-subjects`?
