### ISSUE TITLE
Add rxjs-all-subjects-suffixed rule

### ISSUE THREAD

**Issue by maggie-x** [cartant/rxjs-tslint-rules#75]
I have another rule addition suggestion:

`rxjs-all-subjects-suffixed` (or `rxjs-no-unsuffixed-subjects` as per your naming convention), which enforces that subject names must be suffixed with `Subject$` (also as per the Finnish notation rule). 

e.g.

```
class Mock {
  private property$ = new Rx.Subject<any>();
          ~~~~~~~~~                   [Subject 'property$' must end with 'Subject$']
}
```

Let me know if this is also of interest to integrate. :smile:

**Comment by cartant** [comment]
Yeah. In general, I'm happy to have rules added to the package. They don't have to conform to my opinions - e.g. I'm not a fan of Finnish notation. My only criteria is that they should do what they're intended to do in all circumstances - or, at least, with as few exceptions as possible.

When writing you new rule, you might want to have a look at Craig's [`tsquery` package](https://github.com/phenomnomnominal/tsquery). I favour it over using a walker and I've used to for all of my most recent rules, e.g.:

* https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoCompatRule.ts
* https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoIgnoredNotifierRule.ts

Craig has written about it [here](https://medium.com/@phenomnominal/custom-typescript-lint-rules-with-tsquery-and-tslint-144184b6ff2d).

**Comment by cartant** [comment]
Also, with this one, I think it'll be important for the suffix to be configurable - i.e. via an option.

**Comment by aboyton** [comment]
tsquery package is interesting. I'll need to check it out more. Can you write rules that need to inspect the type of the variable?

I assume you've seen the TypeScript Roadmap: January - June 2019—https://github.com/Microsoft/TypeScript/issues/29288 and recent effort in https://github.com/typescript-eslint/typescript-eslint to allow ESLint to parse TypeScript code and check the type information from the TypeScript compiler?

**Comment by cartant** [comment]
@aboyton

> Can you write rules that need to inspect the type of the variable?

Not yet. I've spoken with the package's author about it - and I have some ideas regarding an implementation - but it's not yet possible. The most significant hurdle is exposing the type information in a manner that doesn't involve introducing a query syntax that's not compatible with `esquery` - as the author does not want the `tsquery` to diverge. I guess that means that the type information needs to be exposed as a lazily-evaluated attribute. However, that's complicated, as types can extend types. E.g. a `BehaviorSubject` is a `Subject`. So for it to be useful for all of the scenarios in which type information is used in `rxjs-tslint-rules` is ... tricky.

I started thinking about adding a mechanism for querying type information when I had a look at the results of the following query when I was talking with Tim Deschryver about an article he was writing:

https://bigtsquery.firebaseapp.com/query?selector=CallExpression%5Bexpression.name.name%3D%22pipe%22%5D%20%3E%20CallExpression%20%3E%20Identifier

The query doesn't just  just find RxJS `pipe` calls; it also picks out several `pipe` calls made on Node streams.

The article is [here](https://blog.angularindepth.com/bending-tslint-to-your-needs-6ae0a51e633), if you're interested.

> I assume you've seen the TypeScript Roadmap

Yeah, but I'll wait until there's some tried and tested infrastructure in place before I start messing with it.

**Comment by cartant** [comment]
Closed by https://github.com/cartant/rxjs-tslint-rules/pull/77
