### ISSUE TITLE
rxjs-no-exposed-subjects could allow protected

### ISSUE THREAD

**Issue by Ristaaf** [cartant/rxjs-tslint-rules#90]
The rxjs-no-exposed-subjects is a great rule that we just implemented in our codebase had a couple of weeks cleanup time to make it pass :) It mostly went fine, but we ran into one problem which is solvable, but I think the solution is less elegant than not solving it. It would be great to hear your opinions on it!

Basically we use inheritance in our code, and have abstract classes that might contain Subjects that are supposed to be overridden in the classes that implements the abstract classes. The convention then is that these Subjects should not be public or private but be protected (available both in the abstract class and any class that impements it). However this is not allowed by the rule, as all Subjects needs to be private!

From my point of view the rule should change so that all Subjects needs to be private or protected.

**Comment by cartant** [comment]
When Maggie implemented this rule, her initial name for it was `rxjs-all-subjects-private` - see #72. I suggested changing the name, as I envisaged someone asking for protected to be supported - at which time an option could be added. It seems that you are that person and now is the time. I'll see what I can do.

**Comment by cartant** [comment]
The just-published 4 .21.0 version should have an `allowProtected` option for the rule.
